[package]
name = "rvtime-compiler"
description = "Codegen backends, guest memory, and trap handling for rvtime"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[build-dependencies]
cc.workspace = true

[dependencies]
anyhow.workspace = true
rv.workspace = true
cranelift.workspace = true
cranelift-codegen.workspace = true
libc.workspace = true
translator.workspace = true
tracing.workspace = true
