[workspace]
members = [
    "crates/core",
    "crates/cranelift",
    "crates/compiler",
    "crates/rvtime",
]
exclude = ["crates/guest"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.0.1"
repository = "https://github.com/crabtalk/rvtime"
license = "Apache-2.0"
authors = ["clearloop <tianyi.gc@gmail.com>"]

[workspace.dependencies]
rv = { path = "crates/core", package = "rvtime-core", version = "0.0.1" }
translator = { path = "crates/cranelift", package = "rvtime-cranelift", version = "0.0.1" }
compiler = { path = "crates/compiler", package = "rvtime-compiler", version = "0.0.1" }
rvtime = { path = "crates/rvtime", package = "rvtime", version = "0.0.1" }
guest = { path = "crates/guest", package = "rvtime-guest", version = "0.0.1" }

# crates-io
anyhow = "1.0"
cc = "1.4"
cranelift = { version = "0.134.3", features = [
    "jit",
    "module",
    "object",
    "native",
    "frontend",
] }
cranelift-codegen = { version = "0.134.3", features = ["incremental-cache"] }
libc = "0.2"
object = "0.40"
tracing = "0.1"
