[package]
name = "rvtime-cranelift"
description = "Translates RV64IMAC into Cranelift IR, one CLIF function per RISC-V function"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
rv.workspace = true
cranelift.workspace = true
cranelift-codegen.workspace = true
tracing.workspace = true
