[package]
name = "berm-api"
description = "What a program says it is, and what bermd's control API speaks"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
object.workspace = true
serde.workspace = true
serde_json.workspace = true
